apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: latex-certificate
spec:
  secretName: latex-certificate
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - *.aivazis.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - *.aivazis.com
